# Copyright 2024 AboveCloud9.AI Products and Services Private Limited
# All rights reserved.
# This code may not be used, copied, modified, or distributed without explicit permission.
services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_USER: glad_user
      POSTGRES_PASSWORD: glad1234
    ports:
      - "5432:5432"
    volumes:
      - ./ops/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    container_name: glad-postgres
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glad_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pushd-db-pg:
    image: postgres:15.8
    environment:
      POSTGRES_USER: glad_user
      POSTGRES_PASSWORD: glad1234
    ports:
      - "5442:5432"
    volumes:
      - ./services/pushd/ops/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pushd_db_pg_data:/var/lib/postgresql/data
    container_name: glad-pushd-pg
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glad_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  ldsd-db-pg:
    image: postgres:15.8
    environment:
      POSTGRES_USER: glad_user
      POSTGRES_PASSWORD: glad1234
    ports:
      - "5452:5432"
    volumes:
      - ./services/ldsd/ops/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ldsd_db_pg_data:/var/lib/postgresql/data
    container_name: glad-ldsd-pg
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glad_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  coursed:
    image: coursed:dev
    environment:
      # ME: coursed
      DB_USER: glad_user
      DB_PASSWORD: glad1234
      DB_DATABASE: glad
      # TODO: localhost to be changed to DB hostname instead cluster
      DB_HOST: postgres
      DB_PORT: 5432
      DB_SSLMODE: disable # require
      API_PORT: 8080
      # URL_HOST: url:8090
    expose:
      - 8080
    ports:
      - "8080:8080"
    container_name: glad-coursed
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  sfsyncd:
    image: sfsyncd:dev
    environment:
      # ME: sfsyncd
      API_PORT: 8080
      COURSED_ADDR: coursed:8080
    expose:
      - 8080
    ports:
      - "8090:8080"
    container_name: glad-sfsyncd
    networks:
      - default

  mediad:
    image: mediad:dev
    environment:
      # ME: mediad
      API_PORT: 8080
      COURSED_ADDR: coursed:8080
    expose:
      - 8080
    ports:
      - "8010:8080"
    container_name: glad-mediad
    networks:
      - default

  ldsd:
    image: ldsd:dev
    environment:
      # ME: ldsd
      DB_PORT: 5452
      API_PORT: 8080
      COURSED_ADDR: coursed:8080
    expose:
      - 8080
    ports:
      - "8020:8080"
    container_name: glad-ldsd
    networks:
      - default
    depends_on:
      ldsd-db-pg:
        condition: service_healthy

  gcd:
    image: gcd:dev
    environment:
      # ME: gcd
      API_PORT: 8080
      COURSED_ADDR: coursed:8080
    expose:
      - 8080
    ports:
      - "8030:8080"
    container_name: glad-gcd
    networks:
      - default

  pushd:
    image: pushd:dev
    environment:
      # ME: pushd
      DB_PORT: 5442
      API_PORT: 8080
      COURSED_ADDR: coursed:8080
    expose:
      - 8080
    ports:
      - "8040:8080"
    container_name: glad-pushd
    networks:
      - default
    depends_on:
      pushd-db-pg:
        condition: service_healthy

  # bastian:
  #   image: alpine:latest
  #   networks:
  #     - default
  #   command: sleep 3600

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: glad-grafana
    networks:
      - default
    depends_on:
      - prometheus
      - prometheus-pushgateway

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: glad-prometheus
    networks:
      - default

  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: glad-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"

volumes:
  postgres_data:
  pushd_db_pg_data:
  ldsd_db_pg_data:

networks:
  default: